POST http://localhost:3000/movies.json 
Content-Type: application/json

{
  "title": "shrek",
  "plot": "green guy find princesss with donkey",
  "year": 2005,
  "director": "dreamworks guy"
  
} 

#################
##### USERS #####
#################

### Users create (signup)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Brandon",
  "email": "brandon@example.com",
  "password": "password",
  "password_confirmation": "password"
}

####################
##### SESSIONS #####
####################

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "AL@example.com",
  "password": "testing"
}