POST http://localhost:3000/movies.json 
Content-Type: application/json

{
  "title": "shrek",
  "plot": "green guy find princesss with donkey",
  "year": 2005,
  "director": "dreamworks guy"
  
} 

#################
##### USERS #####
#################

### Users create (signup)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "David Lin",
  "email": "DL@example.com",
  "password": "testing",
  "password_confirmation": "testing"
}