@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTAxMjI4MzV9.8sfjDahMwwzrSkeRxiim8C-FbVs-zeKnny2p8IquTz4

POST http://localhost:3000/movies.json 
Content-Type: application/json

{
  "title": "shrek",
  "plot": "green guy find princesss with donkey",
  "year": 2005,
  "director": "dreamworks guy"
  
} 

#################
##### USERS #####
#################

### Users create (signup)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Archer",
  "email": "archer@example.com",
  "password": "password",
  "password_confirmation": "password"
}

####################
##### SESSIONS #####
####################

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "archer@example.com",
  "password": "password"
}